### ISSUE TITLE
New, non-pooled thread on player login

### ISSUE THREAD

**Issue by vemacs** [Siguza/VirtualPack#22]
You should be using the Bukkit Scheduler, which has a CachedThreadPool. Instanciating new non-pooled threads can result in a fairly big performance hit. Just runTaskAsync on a BukkitRunnable.

**Comment by Siguza** [comment]
Should (finally) be fixed in dev build 129.
I replaced almost all Threads with equivalent BukkitRunnables except for those on which I need actual Thread methods as Bukkit doesn't seem to provide a `.join()` functionality.
