### ISSUE TITLE
[Suggestion] - Conversion support for PlayerVaults to VirtualPack

### ISSUE THREAD

**Issue by mibby** [Siguza/VirtualPack#23]
Would it be at all possible to convert PlayerVaults chest data (http://dev.bukkit.org/bukkit-plugins/playervaults/) to VirtualPack chests? Player Vaults saves user chest content in a file with their UUID string.

Example file - 0deff483-af1e-457a-8ac9-58f7cfa6e194.yml
http://paste.ubuntu.com/10437750/

**Comment by Siguza** [comment]
Feature added in 15376f83a4464a2dab5e4ccbb5c1fda374eed6d0.

See [here](http://dev.bukkit.org/bukkit-plugins/virtualpack/pages/importing/) for instructions.
