### ISSUE TITLE
[Bug] - Virtual anvil taking more levels than required.

### ISSUE THREAD

**Issue by mibby** [Siguza/VirtualPack#25]
@Siguza 

VirtualPack dev 129
http://ci.siguza.net/job/VirtualPack/129/

Spigot 1.8 git-Spigot-6ee12f6-33d5de3 (Latest compile as of 02/26)

```
  anvil:
    buy: '0'
    use: '0'
    maxlevel: '40'
    cooldown: '0'
```

When trying to use the virtual anvil with /anvil, it ends up taking more levels than listed. Used a normal diamond pickaxe and an unbreaking 2 enchantment book. Stated it required 2 levels, I had 5. When clicking to finalize, it brought my level to 0 but flashed it to 3 just before.

![l1](http://i.imgur.com/k3impfs.png)
![l2](http://i.imgur.com/OPtssv9.png)
![l3](http://i.imgur.com/PzEvorB.png)

Tried it again at level 16. Renamed pick and efficiency 3 book required 4 levels. It brought me down to level 6. I put another pick in the empty slot and the previous enchantment book and pick spawned a duplicate out of nowhere. I didn't have enough levels to re-enchant, but I was able to drag the enchanted pick out and it took another level away from me. Allowing me to enchant without enough levels and duplicating items.

**Comment by Siguza** [comment]
Fixed with 2168801d9437219876f6220cdd9166e61ce35642.
