### ISSUE TITLE
NPE with Uncraft Feature

### ISSUE THREAD

**Issue by BeastsMC** [Siguza/VirtualPack#31]
I keep getting an NPE error after udpating from 2.7.8 to 2.8.1. I have not had time to narrow down what is causing it, but from a quick glance at the relevant method it doesn't seem to be an error that could be cause by any config options or anything I could mess up. So, I thought I'd just post it here.

https://gist.github.com/BeastsMC/c5040a71f2bb504bf16b

And Spigot version:

[03:49:43 INFO]: This server is running CraftBukkit version git-Spigot-52df9dd-ab309d7 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)

**Comment by Siguza** [comment]
Thanks, I'll look into it.
Looks like [`VUncrafterInv.init()`](https://github.com/Siguza/VirtualPack/blob/master/src/main/java/net/drgnome/virtualpack/components/VUncrafterInv.java#L43) is never called, but I can't figure out why, as it should be called from a `BukkitRunnable` in [`VPlugin.registerThreads()`](https://github.com/Siguza/VirtualPack/blob/master/src/main/java/net/drgnome/virtualpack/VPlugin.java#L175)...

**Comment by Siguza** [comment]
Is this still reproducible with 2.8.3 on any server from 1.8 through 1.9?

**Comment by Siguza** [comment]
Closing this due to lack of response.
