### ISSUE TITLE
Uncrafter blacklist

### ISSUE THREAD

**Issue by mibby** [Siguza/VirtualPack#40]
Is it possible to add items to a blacklist to prevent it from being uncrafted? I'd like to blacklist banners from being uncrafted since they can be cloned normally and cheaply in vanilla gameplay. Someone could make an extensive pattern that uses expensive materials, then clone a bunch of banners to uncraft for easy resources.

**Comment by Siguza** [comment]
First off, I'm pretty sure the uncrafter considers only the item and data ID, thus yielding only wool and sticks when uncrafting. My tests seemed to confirm this, although I didn't really do thorough testing.

But yes, you can blacklist banners:

    blacklist:
      uncrafter:
        whitelist: 'false'
        list:
        - BANNER:*

**Comment by Siguza** [comment]
Does this resolve your issue?

**Comment by mibby** [comment]
Yep, thanks! :)
